Document: snapman
Title: Debian snapman Manual
Author: <insert document author here>
Abstract: This manual describes what snapman is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/snapman/snapman.sgml.gz

Format: postscript
Files: /usr/share/doc/snapman/snapman.ps.gz

Format: text
Files: /usr/share/doc/snapman/snapman.text.gz

Format: HTML
Index: /usr/share/doc/snapman/html/index.html
Files: /usr/share/doc/snapman/html/*.html
